## Strict Validation Profile Configuration
## This configuration sets up a strict validation profile
## with high thresholds for critical projects

validation:
  profile: strict
  test_frameworks:
    - pytest
    - unittest
  linters:
    - flake8
    - pylint
  type_checkers:
    - mypy
  timeout: 120
  report_format: json

agents:
  test_validation:
    enabled: true
    result_analysis: true
    coverage_threshold: 90  # High coverage requirement
  code_quality:
    enabled: true
    complexity_threshold: 7  # Stricter complexity limit
    style_check: true
  performance:
    enabled: true  # Performance tests are required
    benchmark_iterations: 5
  security:
    enabled: true  # Security scanning is required
    vulnerability_scan: true
    dependency_check: true

sequential_thinking:
  enabled: true
  max_steps: 15  # More thinking steps allowed
  thought_persistence: true

logging:
  level: DEBUG  # More detailed logging
  file: "validation.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
